import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

interface OrderForPDF {
    id: string;
    createdAt: Date;
    patient: {
        firstName: string;
        lastName: string;
        address: string;
        phone: string;
        email: string;
    };
    lines: {
        product: { name: string; hcpcsCode: string };
        quantity: number;
    }[];
}

const NAVY = rgb(0.06, 0.18, 0.36);
const DARK_GRAY = rgb(0.25, 0.25, 0.3);
const WHITE = rgb(1, 1, 1);
const BLACK = rgb(0, 0, 0);

export async function generateProofOfDeliveryPDF(order: OrderForPDF): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const helveticaOblique = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

    const page = pdfDoc.addPage([612, 792]); // Letter size
    const { width, height } = page.getSize();
    const margin = 48;
    let y = height - margin;

    // ─── Header Band ───────────────────────────────────────────
    page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: NAVY });

    page.drawText('MEDICAL SUPPLY OMS', { x: margin, y: height - 32, size: 18, font: helveticaBold, color: WHITE });
    page.drawText('PROOF OF DELIVERY (POD)', { x: margin, y: height - 52, size: 11, font: helvetica, color: rgb(0.7, 0.85, 0.95) });

    const orderId = `Order #${order.id.slice(-8).toUpperCase()}`;
    const orderIdWidth = helveticaBold.widthOfTextAtSize(orderId, 10);
    page.drawText(orderId, { x: width - margin - orderIdWidth, y: height - 32, size: 10, font: helveticaBold, color: WHITE });

    y = height - 110;

    // ─── Patient Information ────────────────────────────────────
    page.drawText('DELIVER TO:', { x: margin, y, size: 9, font: helveticaBold, color: DARK_GRAY });
    y -= 14;
    page.drawText(`${order.patient.firstName} ${order.patient.lastName}`, { x: margin, y, size: 9, font: helvetica, color: BLACK });
    y -= 14;
    page.drawText(order.patient.address, { x: margin, y, size: 9, font: helvetica, color: BLACK });
    y -= 14;
    page.drawText(order.patient.phone, { x: margin, y, size: 9, font: helvetica, color: BLACK });

    y -= 40;

    // ─── Products Delivered ─────────────────────────────────────
    page.drawText('ITEMS DELIVERED', { x: margin, y, size: 9, font: helveticaBold, color: DARK_GRAY });
    y -= 14;

    order.lines.forEach((line) => {
        page.drawText(`• ${line.quantity}x ${line.product.name} (HCPCS: ${line.product.hcpcsCode})`, { x: margin, y, size: 9, font: helvetica, color: BLACK });
        y -= 14;
    });

    y -= 40;

    // ─── DocuSign Placeholder ───────────────────────────────────
    page.drawRectangle({ x: margin, y: y - 80, width: width - margin * 2, height: 80, borderColor: rgb(0.8, 0.8, 0.8), borderWidth: 2, color: rgb(0.98, 0.98, 0.98) });
    page.drawText('DOCUSIGN INTEGRATION PENDING', { x: margin + 12, y: y - 20, size: 10, font: helveticaBold, color: rgb(0.2, 0.4, 0.8) });
    page.drawText('Patient signature block will be automatically inserted here in a', { x: margin + 12, y: y - 40, size: 9, font: helveticaOblique, color: DARK_GRAY });
    page.drawText('future release via the DocuSign eSignature API.', { x: margin + 12, y: y - 56, size: 9, font: helveticaOblique, color: DARK_GRAY });

    y -= 120;

    // Static signature line
    page.drawText('Patient Signature:', { x: margin, y, size: 9, font: helveticaBold, color: BLACK });
    page.drawLine({ start: { x: margin + 90, y: y - 2 }, end: { x: margin + 290, y: y - 2 }, thickness: 1, color: BLACK });

    page.drawText('Date:', { x: margin + 320, y, size: 9, font: helveticaBold, color: BLACK });
    page.drawLine({ start: { x: margin + 350, y: y - 2 }, end: { x: margin + 450, y: y - 2 }, thickness: 1, color: BLACK });


    // ─── Footer ──────────────────────────────────────────────────
    page.drawText(`Generated by Medical Supply OMS  •  Order ID: ${order.id}  •  ${new Date().toISOString()}`, {
        x: margin, y: 46, size: 7, font: helvetica, color: rgb(0.5, 0.5, 0.5)
    });

    const pdfBytes = await pdfDoc.save();
    return pdfBytes;
}
